import { Trainer, Specialty, UserProfile, Conversation } from './types';

export const CITIES: string[] = [
  'Tel Aviv',
  'Jerusalem',
  'Haifa',
  'Rishon LeZion',
  'Petah Tikva',
  'Ashdod',
  'Netanya',
  'Beersheba',
  'Holon',
  'Bnei Brak',
  'Ramat Gan',
  'Rehovot',
  'Ashkelon',
  'Bat Yam',
  'Herzliya',
  'Kfar Saba',
  'Modiin',
  'Eilat',
];

export const MOCK_TRAINERS: Trainer[] = [
  {
    id: 1,
    name: 'Gal Levi',
    email: 'gal.levi@fasta.com',
    photoUrl: 'https://picsum.photos/seed/gal/400/400',
    specialties: [Specialty.Weightlifting, Specialty.Nutrition],
    hourlyRate: 250,
    location: 'Tel Aviv',
    isOnline: true,
    bio: 'Certified strength and conditioning specialist with a passion for helping clients in Tel Aviv achieve their peak performance and nutritional goals.',
    coordinates: { lat: 32.0853, lng: 34.7818 },
    reviews: [
      { id: 1, author: '@yossic', rating: 5, comment: 'Gal is amazing! Pushed me to my limits and helped me reach my goals faster than I thought possible.' },
      { id: 2, author: '@saras', rating: 5, comment: 'Very knowledgeable about nutrition. The meal plans were a game-changer.' },
      { id: 3, author: '@aviromano', rating: 4, comment: 'Great coach, very motivating sessions.' },
    ],
  },
  {
    id: 2,
    name: 'Tamar Cohen',
    email: 'tamar.cohen@fasta.com',
    photoUrl: 'https://picsum.photos/seed/tamar/400/400',
    specialties: [Specialty.Yoga, Specialty.Pilates],
    hourlyRate: 200,
    location: 'Jerusalem',
    isOnline: true,
    bio: 'Experienced yoga instructor focusing on mindfulness, flexibility, and core strength through Vinyasa and Hatha styles in the heart of Jerusalem.',
    coordinates: { lat: 31.7683, lng: 35.2137 },
    reviews: [
      { id: 4, author: '@rachelm', rating: 5, comment: 'Tamar\'s yoga classes are a sanctuary. I leave feeling refreshed and centered every time.' },
      { id: 5, author: '@davidg', rating: 5, comment: 'Her pilates instruction corrected my posture and eliminated my back pain. Highly recommended.' },
    ],
  },
  {
    id: 3,
    name: 'Lior Shemesh',
    email: 'lior.shemesh@fasta.com',
    photoUrl: 'https://picsum.photos/seed/lior/400/400',
    specialties: [Specialty.CrossFit, Specialty.Cardio],
    hourlyRate: 280,
    location: 'Haifa',
    isOnline: false,
    bio: 'Level 2 CrossFit coach in Haifa, dedicated to high-intensity functional training that pushes limits and builds a strong community.',
    coordinates: { lat: 32.7940, lng: 34.9896 },
    reviews: [
      { id: 6, author: '@noab', rating: 5, comment: 'The toughest workouts with the best coach. Lior knows how to motivate the whole group.' },
      { id: 7, author: '@benk', rating: 4, comment: 'Hardcore sessions. Not for the faint of heart, but the results are incredible.' },
    ],
  },
  {
    id: 4,
    name: 'Shira Azulay',
    email: 'shira.azulay@fasta.com',
    photoUrl: 'https://picsum.photos/seed/shira/400/400',
    specialties: [Specialty.Running, Specialty.Cardio],
    hourlyRate: 220,
    location: 'Herzliya',
    isOnline: true,
    bio: 'Marathon runner and certified coach specializing in endurance training, from 5Ks to ultra-marathons. Let\'s hit the pavement in Herzliya!',
    coordinates: { lat: 32.1663, lng: 34.8433 },
    reviews: [
      { id: 8, author: '@danaa', rating: 5, comment: 'Shira helped me prepare for my first marathon. Her training plan was perfect and she was so supportive.' },
      { id: 9, author: '@omerd', rating: 5, comment: 'Improved my running form and speed significantly.' },
    ],
  },
  {
    id: 5,
    name: 'Ido Peretz',
    email: 'ido.peretz@fasta.com',
    photoUrl: 'https://picsum.photos/seed/ido/400/400',
    specialties: [Specialty.Boxing, Specialty.Weightlifting],
    hourlyRate: 300,
    location: 'Rishon LeZion',
    isOnline: false,
    bio: 'Former amateur boxer providing intense boxing workouts that improve footwork, power, and overall fitness in Rishon LeZion.',
    coordinates: { lat: 31.9730, lng: 34.7925 },
    reviews: [
      { id: 10, author: '@mayad', rating: 5, comment: 'An incredible workout and a great way to relieve stress. Ido is a fantastic boxing coach.' },
    ],
  },
  {
    id: 6,
    name: 'Noga Elkayam',
    email: 'noga.elkayam@fasta.com',
    photoUrl: 'https://picsum.photos/seed/noga/400/400',
    specialties: [Specialty.Nutrition, Specialty.Yoga],
    hourlyRate: 180,
    location: 'Online',
    isOnline: true,
    bio: 'Holistic wellness coach combining nutritional guidance with gentle yoga to create balanced and sustainable lifestyles, available anywhere.',
    reviews: [
      { id: 11, author: '@adio', rating: 5, comment: 'Noga transformed my relationship with food and exercise. Her approach is so kind and effective.' },
      { id: 12, author: '@talf', rating: 5, comment: 'Perfect for anyone looking for a balanced approach to wellness.' },
    ],
  },
   {
    id: 7,
    name: 'Ron Shavit',
    email: 'ron.shavit@fasta.com',
    photoUrl: 'https://picsum.photos/seed/ron/400/400',
    specialties: [Specialty.Weightlifting, Specialty.CrossFit],
    hourlyRate: 320,
    location: 'Beersheba',
    isOnline: true,
    bio: 'Powerlifting competitor and coach in Beersheba focused on building raw strength and perfecting form for major lifts like squat, bench, and deadlift.',
    coordinates: { lat: 31.2530, lng: 34.7915 },
    reviews: [
      { id: 13, author: '@amirs', rating: 5, comment: 'If you want to get strong, Ron is the guy. No nonsense, just results.' },
    ],
  },
  {
    id: 8,
    name: 'Hila Gabay',
    email: 'hila.gabay@fasta.com',
    photoUrl: 'https://picsum.photos/seed/hila/400/400',
    specialties: [Specialty.Pilates, Specialty.Cardio],
    hourlyRate: 240,
    location: 'Netanya',
    isOnline: true,
    bio: 'Stott Pilates certified instructor with expertise in reformer and mat exercises for posture and core stability. Sessions available in Netanya and online.',
    coordinates: { lat: 32.3215, lng: 34.8532 },
    reviews: [
        { id: 14, author: '@shanil', rating: 5, comment: 'Hila is a wonderful instructor. Her attention to detail is amazing.' },
        { id: 15, author: '@efratw', rating: 4, comment: 'Challenging but rewarding pilates classes.' },
    ],
  },
  {
    id: 9,
    name: 'Ben Dahan',
    email: 'ben.dahan@fasta.com',
    photoUrl: 'https://picsum.photos/seed/bendahan/400/400',
    specialties: [Specialty.Running, Specialty.Cardio],
    hourlyRate: 230,
    location: 'Eilat',
    isOnline: false,
    bio: 'Endurance athlete and running coach based in Eilat. Let\'s conquer the desert trails together.',
    coordinates: { lat: 29.5577, lng: 34.9519 },
    reviews: [
      { id: 16, author: '@runnergal', rating: 5, comment: 'Ben is an inspiring coach!' },
    ],
  },
  {
    id: 10,
    name: 'Adi Katz',
    email: 'adi.katz@fasta.com',
    photoUrl: 'https://picsum.photos/seed/adikatz/400/400',
    specialties: [Specialty.CrossFit],
    hourlyRate: 310,
    location: 'Ramat Gan',
    isOnline: true,
    bio: 'Push your limits with high-intensity CrossFit workouts. All levels welcome in my Ramat Gan box.',
    coordinates: { lat: 32.0826, lng: 34.8093 },
    reviews: [],
  },
  {
    id: 11,
    name: 'Omer Gabay',
    email: 'omer.gabay@fasta.com',
    photoUrl: 'https://picsum.photos/seed/omergabay/400/400',
    specialties: [Specialty.Boxing, Specialty.Cardio],
    hourlyRate: 290,
    location: 'Holon',
    isOnline: false,
    bio: 'Learn the sweet science of boxing. Improve your coordination, stamina, and confidence in Holon.',
    coordinates: { lat: 32.016, lng: 34.7738 },
    reviews: [
      { id: 17, author: '@fighter88', rating: 5, comment: 'Amazing energy in Omer\'s classes.' },
      { id: 18, author: '@liatp', rating: 5, comment: 'Best workout I\'ve had in years.' },
    ],
  },
  {
    id: 12,
    name: 'Yael Peretz',
    email: 'yael.peretz@fasta.com',
    photoUrl: 'https://picsum.photos/seed/yaelperetz/400/400',
    specialties: [Specialty.Pilates],
    hourlyRate: 210,
    location: 'Kfar Saba',
    isOnline: true,
    bio: 'Strengthen your core and improve your posture with classical Pilates. Sessions in Kfar Saba and online.',
    coordinates: { lat: 32.174, lng: 34.908 },
    reviews: [
      { id: 19, author: '@dalia', rating: 5, comment: 'Yael is a very patient and knowledgeable instructor.' },
    ],
  },
  {
    id: 13,
    name: 'Moshe Avraham',
    email: 'moshe.avraham@fasta.com',
    photoUrl: 'https://picsum.photos/seed/mosheavraham/400/400',
    specialties: [Specialty.Nutrition, Specialty.Weightlifting],
    hourlyRate: 270,
    location: 'Petah Tikva',
    isOnline: true,
    bio: 'Achieve your body composition goals with a scientific approach to nutrition and strength training in Petah Tikva.',
    coordinates: { lat: 32.086, lng: 34.8876 },
    reviews: [
      { id: 20, author: '@healthyfoodie', rating: 5, comment: 'Moshe really knows his stuff. The meal plans are easy to follow.' },
    ],
  },
  {
    id: 14,
    name: 'Shay Biton',
    email: 'shay.biton@fasta.com',
    photoUrl: 'https://picsum.photos/seed/shaybiton/400/400',
    specialties: [Specialty.Yoga],
    hourlyRate: 190,
    location: 'Rehovot',
    isOnline: true,
    bio: 'Find your inner peace and flexibility with Hatha and Yin yoga classes in Rehovot.',
    coordinates: { lat: 31.8928, lng: 34.8113 },
    reviews: [],
  },
  {
    id: 15,
    name: 'Danielle David',
    email: 'danielle.david@fasta.com',
    photoUrl: 'https://picsum.photos/seed/danielledavid/400/400',
    specialties: [Specialty.Cardio, Specialty.Running],
    hourlyRate: 220,
    location: 'Ashdod',
    isOnline: false,
    bio: 'High-energy cardio classes and running groups by the Ashdod coast. Let\'s get moving!',
    coordinates: { lat: 31.8043, lng: 34.6553 },
    reviews: [
      { id: 21, author: '@marathonman', rating: 4, comment: 'Fun group runs!' },
    ],
  },
  {
    id: 16,
    name: 'Matan Shemesh',
    email: 'matan.shemesh@fasta.com',
    photoUrl: 'https://picsum.photos/seed/matanshemesh/400/400',
    specialties: [Specialty.CrossFit, Specialty.Weightlifting],
    hourlyRate: 330,
    location: 'Ashkelon',
    isOnline: false,
    bio: 'Functional fitness for real-world strength. Join our supportive CrossFit community in Ashkelon.',
    coordinates: { lat: 31.6693, lng: 34.5715 },
    reviews: [
      { id: 22, author: '@fitterme', rating: 5, comment: 'Matan is a beast! Pushes you to be your best.' },
    ],
  },
  {
    id: 17,
    name: 'Michal Dahan',
    email: 'michal.dahan@fasta.com',
    photoUrl: 'https://picsum.photos/seed/michaldahan/400/400',
    specialties: [Specialty.Pilates, Specialty.Yoga],
    hourlyRate: 230,
    location: 'Modiin',
    isOnline: true,
    bio: 'Specializing in pre-natal and post-natal Pilates and yoga. Nurturing classes in Modiin.',
    coordinates: { lat: 31.903, lng: 35.009 },
    reviews: [
      { id: 23, author: '@newmom', rating: 5, comment: 'Michal was amazing throughout my pregnancy.' },
    ],
  },
  {
    id: 18,
    name: 'Guy Friedman',
    email: 'guy.friedman@fasta.com',
    photoUrl: 'https://picsum.photos/seed/guyfriedman/400/400',
    specialties: [Specialty.Weightlifting],
    hourlyRate: 280,
    location: 'Tel Aviv',
    isOnline: true,
    bio: 'Old-school bodybuilding and powerlifting coach. If you want to build serious muscle, I\'m your guy.',
    coordinates: { lat: 32.0853, lng: 34.7818 },
    reviews: [],
  },
  {
    id: 19,
    name: 'Keren Mizrahi',
    email: 'keren.mizrahi@fasta.com',
    photoUrl: 'https://picsum.photos/seed/kerenmizrahi/400/400',
    specialties: [Specialty.Nutrition],
    hourlyRate: 200,
    location: 'Online',
    isOnline: true,
    bio: 'Certified nutritionist specializing in intuitive eating and healthy lifestyle changes. Online consultations available.',
    reviews: [
      { id: 24, author: '@sara_b', rating: 5, comment: 'Keren helped me heal my relationship with food. So grateful.' },
    ],
  },
  {
    id: 20,
    name: 'Tal Azulay',
    email: 'tal.azulay@fasta.com',
    photoUrl: 'https://picsum.photos/seed/talazulay/400/400',
    specialties: [Specialty.Boxing],
    hourlyRate: 260,
    location: 'Haifa',
    isOnline: true,
    bio: 'High-intensity boxing fitness classes in Haifa that will get you sweating and feeling powerful.',
    coordinates: { lat: 32.7940, lng: 34.9896 },
    reviews: [
      { id: 25, author: '@boxfan', rating: 4, comment: 'Great workout, very intense.' },
    ],
  },
  {
    id: 21,
    name: 'Noam Katz',
    email: 'noam.katz@fasta.com',
    photoUrl: 'https://picsum.photos/seed/noamkatz/400/400',
    specialties: [Specialty.Running],
    hourlyRate: 210,
    location: 'Jerusalem',
    isOnline: false,
    bio: 'Running coach for all levels, specializing in trail running in the Jerusalem hills.',
    coordinates: { lat: 31.7683, lng: 35.2137 },
    reviews: [],
  },
  {
    id: 22,
    name: 'Moran Shavit',
    email: 'moran.shavit@fasta.com',
    photoUrl: 'https://picsum.photos/seed/moranshavit/400/400',
    specialties: [Specialty.Weightlifting, Specialty.Nutrition],
    hourlyRate: 300,
    location: 'Herzliya',
    isOnline: true,
    bio: 'ISSA certified elite trainer focusing on body transformation through strength and nutrition.',
    coordinates: { lat: 32.1663, lng: 34.8433 },
    reviews: [
      { id: 26, author: '@getfit', rating: 5, comment: 'Moran is a pro. The results speak for themselves.' },
    ],
  },
  {
    id: 23,
    name: 'Idan Cohen',
    email: 'idan.cohen@fasta.com',
    photoUrl: 'https://picsum.photos/seed/idancohen/400/400',
    specialties: [Specialty.Cardio],
    hourlyRate: 180,
    location: 'Rishon LeZion',
    isOnline: true,
    bio: 'High-energy HIIT and aerobics classes that are fun and effective. Join me in Rishon!',
    coordinates: { lat: 31.9730, lng: 34.7925 },
    reviews: [],
  },
  {
    id: 24,
    name: 'Eden Levi',
    email: 'eden.levi@fasta.com',
    photoUrl: 'https://picsum.photos/seed/edenlevi/400/400',
    specialties: [Specialty.Yoga],
    hourlyRate: 200,
    location: 'Tel Aviv',
    isOnline: true,
    bio: 'Ashtanga and Power Yoga instructor. Dynamic and challenging classes for deepening your practice.',
    coordinates: { lat: 32.0853, lng: 34.7818 },
    reviews: [
      { id: 27, author: '@yogi_dan', rating: 5, comment: 'Eden\'s classes are powerful and transformative.' },
    ],
  },
  {
    id: 25,
    name: 'Tomer Biton',
    email: 'tomer.biton@fasta.com',
    photoUrl: 'https://picsum.photos/seed/tomerbiton/400/400',
    specialties: [Specialty.CrossFit],
    hourlyRate: 320,
    location: 'Beersheba',
    isOnline: false,
    bio: 'Building a strong and resilient community through CrossFit in Beersheba.',
    coordinates: { lat: 31.2530, lng: 34.7915 },
    reviews: [
      { id: 28, author: '@crossfitter', rating: 5, comment: 'Great box, great coach.' },
    ],
  },
  {
    id: 26,
    name: 'Sharon Gabay',
    email: 'sharon.gabay@fasta.com',
    photoUrl: 'https://picsum.photos/seed/sharongabay/400/400',
    specialties: [Specialty.Pilates, Specialty.Nutrition],
    hourlyRate: 250,
    location: 'Netanya',
    isOnline: true,
    bio: 'Holistic approach to fitness, combining mindful movement from Pilates with balanced nutrition.',
    coordinates: { lat: 32.3215, lng: 34.8532 },
    reviews: [],
  },
  {
    id: 27,
    name: 'Elad Peretz',
    email: 'elad.peretz@fasta.com',
    photoUrl: 'https://picsum.photos/seed/eladperetz/400/400',
    specialties: [Specialty.Boxing],
    hourlyRate: 280,
    location: 'Haifa',
    isOnline: false,
    bio: 'Technical boxing coach focusing on footwork, defense, and combination punching.',
    coordinates: { lat: 32.7940, lng: 34.9896 },
    reviews: [
      { id: 29, author: '@boxing_life', rating: 5, comment: 'Learned so much from Elad about proper technique.' },
    ],
  },
  {
    id: 28,
    name: 'Vered Friedman',
    email: 'vered.friedman@fasta.com',
    photoUrl: 'https://picsum.photos/seed/veredfriedman/400/400',
    specialties: [Specialty.Yoga, Specialty.Pilates],
    hourlyRate: 210,
    location: 'Bat Yam',
    isOnline: true,
    bio: 'Find your center and build your core strength with Vered\'s combined yoga and pilates sessions. Available in Bat Yam and online.',
    coordinates: { lat: 32.0171, lng: 34.7454 },
    reviews: [],
  },
];

export const MOCK_USERS: { [key: string]: UserProfile } = {
  'yossi.cohen@example.com': {
    email: 'yossi.cohen@example.com',
    fullName: 'Yossi Cohen',
    username: 'yossic',
    photoUrl: 'https://picsum.photos/seed/yossic/200/200',
    completedSessions: 5,
    earnedMedalIds: ['first_step', 'consistent_contender'],
    conversations: [], // This will be populated by App.tsx
    favoriteTrainerIds: [1, 4],
  },
  'sara.levi@example.com': {
    email: 'sara.levi@example.com',
    fullName: 'Sara Levi',
    username: 'saras',
    photoUrl: 'https://picsum.photos/seed/saras/200/200',
    completedSessions: 1,
    earnedMedalIds: ['first_step'],
    conversations: [], // This will be populated by App.tsx
    favoriteTrainerIds: [2],
  }
};

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    participants: [
      { id: 'yossi.cohen@example.com', name: 'Yossi Cohen', photoUrl: 'https://picsum.photos/seed/yossic/200/200' },
      { id: 'gal.levi@fasta.com', name: 'Gal Levi', photoUrl: 'https://picsum.photos/seed/gal/400/400' }
    ],
    messages: [
      { id: 'msg-1', senderId: 'yossi.cohen@example.com', content: 'Hey Gal, loved the session today!', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), read: true },
      { id: 'msg-2', senderId: 'gal.levi@fasta.com', content: 'Glad to hear it, Yossi! You did great. See you next week.', timestamp: new Date(Date.now() - 1000 * 60 * 55 * 2).toISOString(), read: false },
    ]
  },
  {
    id: 'conv-2',
    participants: [
      { id: 'sara.levi@example.com', name: 'Sara Levi', photoUrl: 'https://picsum.photos/seed/saras/200/200' },
      { id: 'tamar.cohen@fasta.com', name: 'Tamar Cohen', photoUrl: 'https://picsum.photos/seed/tamar/400/400' }
    ],
    messages: []
  }
];